[package]
name = "looker"
version = "0.1.0"
edition = "2021"

[dependencies]
indexer = { path = "../indexer" }
clap = {verison="4.1.11", features = ["cargo"]}
dotenv = "0.15.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.64"
directories = "5.0.1"